rbino/tigerbeetlex

README.md

Adds a contributing section with instructions setting up locally

add a contributing section

---

.github/workflows/main.yml
build.zig
mix.exs
mix.lock
scripts/build.sh
scripts/build_runner.zig
src/tigerbeetlex.zig

Add Mac Support

---

.github/workflows/main.yml

Test on latest versions of OTP and Elixir

Add otp-26 and Elixir 1.15.2 to the CI

---

lib/tigerbeetlex/account.ex
lib/tigerbeetlex/account_batch.ex
lib/tigerbeetlex/id_batch.ex
lib/tigerbeetlex/nif_adapter.ex
lib/tigerbeetlex/transfer.ex
lib/tigerbeetlex/transfer_batch.ex
lib/tigerbeetlex/types.ex
src/account_batch.zig
src/batch.zig
src/id_batch.zig
src/tigerbeetlex.zig
src/transfer_batch.zig
test/tigerbeetlex/account_batch_test.exs
test/tigerbeetlex/account_test.exs
test/tigerbeetlex/id_batch_test.exs
test/tigerbeetlex/transfer_batch_test.exs
test/tigerbeetlex/transfer_test.exs

Allow retrieving elements from them.
Close #7

Add fetch function to batches

---

lib/tigerbeetlex/account.ex
lib/tigerbeetlex/create_account_error.ex
lib/tigerbeetlex/create_transfer_error.ex
lib/tigerbeetlex/id_batch.ex
lib/tigerbeetlex/nif_adapter.ex
lib/tigerbeetlex/transfer.ex
lib/tigerbeetlex/types.ex
test/integration_test.exs
test/tigerbeetlex/account_test.exs
test/tigerbeetlex/transfer_test.exs

Change the code to add support for new u128 amounts. Regenerate error enums since they changed too.
Close #33

Update TigerBeetle to 0.13.130

---

.github/dependabot.yml

Just a quick one to add @dependabot to help keep dependencies up-to-date. 🤖 ⬆️ 
Feel free to reject or merge if desired. 👌

PR: add `dependabot.yml` to help maintain dependencies 🤖 

---

lib/tigerbeetlex/transfer.ex
mix.exs

From what I could tell Benchee wasn't required in prod - so I removed that requirement.
I also found a broken link - which I fixed.
I'm completely fine with this being merged or closed - just adding it here if it's useful in anyway to anyone.

Minor changes to make the library easier to use

---

lib/tigerbeetlex.ex
lib/tigerbeetlex/account_filter_batch.ex
lib/tigerbeetlex/connection.ex
lib/tigerbeetlex/nif_adapter.ex
lib/tigerbeetlex/receiver.ex
lib/tigerbeetlex/types.ex
src/account_filter_batch.zig
src/client.zig
src/tigerbeetlex.zig
test/integration_test.exs

Rebased on the fixed CI and generated bindings, supersedes #59

Add  `get_account_balances` and `get_account_transfers`

---

build.zig.zon
src/client.zig
src/config.zig
src/tigerbeetlex.zig
tools/elixir_bindings.zig

- Use the new intrusive client (see https://github.com/tigerbeetle/tigerbeetle/pull/2742)
- Handle `get_events` operation, ignoring it (see https://github.com/tigerbeetle/tigerbeetle/pull/2507)

chore: update TigerBeetle to 0.16.29

---

lib/tigerbeetlex/receiver.ex
test/tigerbeetlex/response_test.exs

Remove useless ones and don't use multi-alias syntax

chore: cleanup aliases

---

.github/workflows/main.yml

Ensure generated bindings are always up to date

feat: check bindings

---

CHANGELOG.md
README.md
lib/tigerbeetlex/connection.ex
lib/tigerbeetlex/id.ex
mix.exs
src/tigerbeetlex.zig

Prepare 0.16.38

---

lib/tigerbeetlex/bindings/create_account_result.ex
lib/tigerbeetlex/bindings/create_transfer_result.ex
mix.exs
tools/elixir_bindings.zig

Some more adjustments before release

Prepare 0.16.38 - Take 2

---

lib/tigerbeetlex/application.ex
lib/tigerbeetlex/client.ex
lib/tigerbeetlex/connection.ex
lib/tigerbeetlex/id.ex
lib/tigerbeetlex/id/server.ex
mix.exs
mix.lock
test/concurrency_test.exs
test/integration_test.exs
test/tigerbeetlex/id_test.exs

Generate TigerBeetle Time-Based Identifiers.
Close #69

feat: add TigerBeetlex.ID.generate/0

---

lib/tigerbeetlex/bindings/transfer.ex
tools/elixir_bindings.zig

Use it to add Transfer.amount_max/0

feat(elixir_bindings): allow generating constants in modules

---

CHANGELOG.md
README.md
build.zig.zon
guides/walkthrough.livemd
mix.exs
src/config.zig

chore: prepare release 0.16.41

---

CHANGELOG.md
guides/change_data_capture.livemd
lib/tigerbeetlex/cdc.ex
lib/tigerbeetlex/cdc/account.ex
lib/tigerbeetlex/cdc/account_flags.ex
lib/tigerbeetlex/cdc/event.ex
lib/tigerbeetlex/cdc/transfer.ex
lib/tigerbeetlex/cdc/transfer_flags.ex
lib/tigerbeetlex/types.ex
mix.exs
test/tigerbeetlex/cdc/account_flags_test.exs
test/tigerbeetlex/cdc/account_test.exs
test/tigerbeetlex/cdc/event_test.exs
test/tigerbeetlex/cdc/transfer_flags_test.exs
test/tigerbeetlex/cdc/transfer_test.exs

Cast TigerBeetle CDC data in a struct and add a guide detailing how to consume CDC data using Broadway

feat: add CDC handling utilities and guide

---

CHANGELOG.md
README.md
build.zig.zon
guides/change_data_capture.livemd
guides/walkthrough.livemd
mix.exs
src/config.zig

chore: prepare release 0.16.47

---

build.zig

chore: remove vsr import from config module

---

CHANGELOG.md
README.md
build.zig
build.zig.zon
guides/change_data_capture.livemd
guides/walkthrough.livemd
lib/tigerbeetlex/bindings/account.ex
lib/tigerbeetlex/bindings/account_filter.ex
lib/tigerbeetlex/bindings/create_accounts_result.ex
lib/tigerbeetlex/bindings/create_transfers_result.ex
lib/tigerbeetlex/bindings/query_filter.ex
lib/tigerbeetlex/bindings/transfer.ex
mix.exs
mix.lock
src/config.zig
test/integration_test.exs
test/tigerbeetlex/connection_test.exs

stdx was extracted to a separate module, recreate it in our build

chore: prepare release 0.16.53
